# Docker for Solving Pack
# Creator: Md. Moshiur Rahman (Moshiur)
# Created Date: 12_02_2025
# Purpose: Easy deployment and setup
# Version: 1.0.1 (Tested by Ubuntu 22.4)

version: "3.8"

services:
    # The Solving Pack Docker Server
    solving_pack_server:
        container_name: solving_pack_server_container
        build:
            context: .
            dockerfile: dockerfile
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./:/app
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            - DB_HOST=solving_pack_db
        command: php -S 0.0.0.0:8001 -t /app/codes

    # The Database
    solving_pack_db:
        container_name: solving_pack_db
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=solving_pack_db
            - MYSQL_ROOT_PASSWORD=password
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 8002:3306

    # PHPMyAdmin
    solving_pack_phpmyadmin:
        container_name: solving_pack_phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            - PMA_HOST=solving_pack_db
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=password
        ports:
            - 8003:80
        depends_on:
            - solving_pack_db
