version: "3.8"

services:
    # The Solutions Application
    solutions_server:
        container_name: solutions_server_container
        build:
            context: .
            dockerfile: dockerfile
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./:/app
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            - DB_HOST=solutions_db
        # command: php -S 0.0.0.0:8001
        command: php -S 0.0.0.0:8001 -t /app/codes

    # The Database
    solutions_db:
        container_name: solutions_db
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=solutions_db
            - MYSQL_ROOT_PASSWORD=password
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 8002:3306

    # PHPMyAdmin
    solutions_phpmyadmin:
        container_name: solutions_phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            - PMA_HOST=solutions_db
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=password
        ports:
            - 8003:80
        depends_on:
            - solutions_db
